import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./page.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/img/favicon.ico" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
